/**
 * Render a `DailyReport` as Markdown. Pure function, deterministic for a
 * given input — no `Date.now()`, no env reads — so tests can pin the output.
 */

import type { DailyReport, ApprovalRecord, EvidenceArtifactCount, ReleaseRecord, RoomScan, NextAction } from "./aggregator.js";

export function renderDailyReportMarkdown(report: DailyReport): string {
  const lines: string[] = [];

  lines.push(`# CONSOLELAB DAILY REPORT — ${report.dayKey}`);
  lines.push("");
  lines.push("> Immutable. Corrections must be filed as a sibling `*_ADDENDUM_YYYY-MM-DD.md` (use `report:daily -- --addendum`).");
  lines.push("");

  // --- Header ---
  lines.push("## Header");
  lines.push("");
  lines.push(`- **Date:** ${report.dayKey}`);
  lines.push(`- **Timezone:** ${report.timeZone}`);
  lines.push(`- **Generated at:** ${report.generatedAt}`);
  lines.push(`- **Repo root:** \`${report.repoRoot}\``);
  lines.push(`- **Git SHA:** ${report.gitSha ? `\`${report.gitSha}\`` + (report.gitShaShort ? ` (\`${report.gitShaShort}\`)` : "") : "_unknown_"}`);
  lines.push("");

  // --- Rooms walked ---
  lines.push("## Rooms Walked");
  lines.push("");
  lines.push("| Room | Subdir | Status | Files matched | Entries matched |");
  lines.push("| --- | --- | --- | ---: | ---: |");
  for (const room of report.rooms) {
    const status = room.exists ? "present" : "MISSING";
    lines.push(`| ${room.room} | ${room.subdir} | ${status} | ${room.matchedFiles} | ${room.matchedEntries} |`);
  }
  lines.push("");

  // --- Evidence stamp summary ---
  lines.push("## Evidence Stamp Summary");
  lines.push("");
  if (report.evidence.every((entry) => entry.total === 0)) {
    lines.push("_No evidence stamps recorded for this date._");
  } else {
    lines.push("| Artifact | Total | First tx_hash | Last tx_hash | Top components |");
    lines.push("| --- | ---: | --- | --- | --- |");
    for (const entry of report.evidence) {
      lines.push(renderEvidenceRow(entry));
    }
  }
  lines.push("");

  // --- Approvals summary ---
  lines.push("## Approvals Summary");
  lines.push("");
  lines.push(`- **Pending:** ${report.approvals.pending.length}`);
  lines.push(`- **Approved:** ${report.approvals.approved.length}`);
  lines.push(`- **Rejected:** ${report.approvals.rejected.length}`);
  lines.push("");
  if (report.approvals.pending.length + report.approvals.approved.length + report.approvals.rejected.length === 0) {
    lines.push("_No approval activity recorded for this date._");
    lines.push("");
  } else {
    lines.push(renderApprovalSection("Pending", report.approvals.pending));
    lines.push(renderApprovalSection("Approved", report.approvals.approved));
    lines.push(renderApprovalSection("Rejected", report.approvals.rejected));
  }

  // --- Release summary ---
  lines.push("## Release Summary");
  lines.push("");
  if (report.releases.length === 0) {
    lines.push("_No release artifacts referenced for this date._");
  } else {
    for (const release of report.releases) {
      lines.push(renderReleaseLine(release));
    }
  }
  lines.push("");

  // --- Activity ---
  lines.push("## Workflow & Command Activity");
  lines.push("");
  lines.push(`- **Workflows touched:** ${report.workflowsTouched}`);
  lines.push(`- **Commands accepted (intake.jsonl):** ${report.commandsIntake}`);
  lines.push(`- **Commands dispatched (execution.jsonl):** ${report.commandsExecution}`);
  lines.push("");

  // --- Next actions ---
  lines.push("## Next Actions");
  lines.push("");
  if (report.nextActions.length === 0) {
    lines.push("_None — every observed item closed cleanly._");
  } else {
    for (const action of report.nextActions) {
      lines.push(renderNextActionLine(action));
    }
  }
  lines.push("");

  // --- Trailer ---
  lines.push("---");
  lines.push("Generated by `scripts/archive/consolab-daily-report.ts`. Sealed by file-system immutability — see `archives/daily/README.md`.");
  lines.push("");

  return lines.join("\n");
}

function renderEvidenceRow(entry: EvidenceArtifactCount): string {
  const components = Object.entries(entry.byComponent)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([name, count]) => `${name}:${count}`)
    .join(", ") || "_none_";
  return `| ${entry.artifact} | ${entry.total} | ${shortHash(entry.firstTxHash)} | ${shortHash(entry.lastTxHash)} | ${components} |`;
}

function shortHash(value: string | null): string {
  if (!value) return "_none_";
  return `\`${value.slice(0, 16)}…\``;
}

function renderApprovalSection(title: string, records: ApprovalRecord[]): string {
  if (records.length === 0) return "";
  const lines: string[] = [];
  lines.push(`### ${title}`);
  lines.push("");
  for (const record of records) {
    const meta = [
      record.action ? `action=${record.action}` : null,
      record.approver ? `by=${record.approver}` : null,
      record.at ? `at=${record.at}` : null
    ]
      .filter(Boolean)
      .join(" • ");
    lines.push(`- \`${record.source}\` :: ${record.trackingId}${meta ? ` — ${meta}` : ""}`);
  }
  lines.push("");
  return lines.join("\n");
}

function renderReleaseLine(release: ReleaseRecord): string {
  const at = release.at ? ` (${release.at})` : "";
  return `- **${release.kind}** — \`${release.source}\`${at} — ${release.detail}`;
}

function renderNextActionLine(action: NextAction): string {
  return `- ${action.reason} — \`${action.ref}\``;
}
